### ISSUE TITLE
Problem: dependencies are not up to date

### ISSUE THREAD

**Issue by thomas-nguy** [crypto-org-chain/gravity-bridge#168]
Cosmos SDK has released a new version (v0.46.6) with bugfixes

**Comment by tomtau** [comment]
@thomas-nguy https://github.com/cosmos/cosmos-sdk/releases/tag/v0.47.0-alpha1
https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/UPGRADING.md
for the cosmos/gogoproto  migration, you can refer to https://github.com/cosmos/cosmos-sdk/pull/13070/files

**Comment by thomas-nguy** [comment]
solved
