### ISSUE TITLE
Problem: the `ethereum` container inside the integration tests fail to build with the current Dockerfile

### ISSUE THREAD

**Issue by farazsth98** [crypto-org-chain/gravity-bridge#188]
The current Dockerfile has some errors with it that prevents the container from being built as is.

Specifically, Dockerfiles are ran using the directory that they're in as the CWD (current working directory). Because of this, the following lines inside the Dockerfile will fail to execute:

```dockerfile
COPY integration_tests/ethereum/package.json package.json
COPY integration_tests/ethereum/yarn.lock yarn.lock
COPY integration_tests/ethereum/ .
COPY solidity/contracts/Gravity.sol contracts/Gravity.sol
COPY solidity/contracts/CosmosToken.sol contracts/CosmosToken.sol
COPY solidity/contracts/ICosmosToken.sol contracts/ICosmosToken.sol
```

I made the following changes to it to get it working. Note that I am working on WSL2 using `docker-desktop` from Windows, so I'm unsure if that has anything to do with the issues.

Diff of changes:

```diff
$ git diff integration_tests/ethereum/Dockerfile
diff --git a/integration_tests/ethereum/Dockerfile b/integration_tests/ethereum/Dockerfile
index 686a80ae..5c7f7cbb 100644
--- a/integration_tests/ethereum/Dockerfile
+++ b/integration_tests/ethereum/Dockerfile
@@ -3,17 +3,17 @@ FROM node:14-alpine3.13
 RUN apk update
 RUN apk add --no-cache git python3 make build-base

-COPY integration_tests/ethereum/package.json package.json
-COPY integration_tests/ethereum/yarn.lock yarn.lock
+COPY package.json package.json
+COPY yarn.lock yarn.lock

 RUN yarn install --production=false
 RUN npm config set user 0

-COPY integration_tests/ethereum/ .
+COPY . .

-COPY solidity/contracts/Gravity.sol contracts/Gravity.sol
-COPY solidity/contracts/CosmosToken.sol contracts/CosmosToken.sol
-COPY solidity/contracts/ICosmosToken.sol contracts/ICosmosToken.sol
+COPY contracts/Gravity.sol contracts/Gravity.sol
+COPY contracts/CosmosToken.sol contracts/CosmosToken.sol
+COPY contracts/ICosmosToken.sol contracts/ICosmosToken.sol


 ENV ARCHIVE_NODE_URL=""
```

For the `Gravity.sol`, `CosmosToken.sol`, and `ICosmosToken.sol` contracts, I copied them over from their actual location (under `solidity/contracts/`).

**Comment by thomas-nguy** [comment]
thanks for the suggestion, will look into it

**Comment by thomas-nguy** [comment]
This dockerfile is supposed to be run from the parent repository (that is how it is built on github CI) that is why the path is relative to the root. 
(or could use `make e2e_build_images`)


For local environment, we may need a proper docker compose that also can be run from root to make it easier

**Comment by farazsth98** [comment]
Ahh ok that makes sense. I was having issues with `make e2e_build_images` from the root, but if github CI works fine with it then that's ok. Just putting it here that attempting to build from the root of the repo with the current Dockerfile failed for me

**Comment by thomas-nguy** [comment]
Hi @farazsth98 , yes you are right, the command is failing

I have created a PR to fix it https://github.com/crypto-org-chain/gravity-bridge/pull/190

The reason to use the root as context is because the contracts (Gravity, CosmosToken, ICosmosToken) are located in a different folder and we want to reference them directly instead of copy/paste everytime there is a change

**Comment by farazsth98** [comment]
Cool, thanks @thomas-nguy , I'll close this issue now since your PR is good.
