### ISSUE TITLE
Add simulation to gravity module

### ISSUE THREAD

**Issue by thomas-nguy** [crypto-org-chain/gravity-bridge#84]
Support simulation for gravity bridge

https://docs.cosmos.network/master/building-modules/simulator.html

**Comment by UrsaarDev** [comment]
HI, @thomas-nguy 
=====================================
 From: Doraemon (209-YS/DESKTOP-1J8HO77/10.10.11.131/Doraemon-<8611feac5cdbfd27>)
  at Wed Jul 27 06:56:19 2022
-------------------------------------
👋🏻 Good day, mates.
I make the following utilities based on Solidity & Rust with powerful frontend demonstration.
💻Dapps(Swap, Staking, Referral, Farm, Pool, Presale, Reflection, DAO ...)
💻NFT marketplaces (Opensea, Rarible, Metaplex)
💻Backend software
Leave msgs if you are in the demand of me.

**Comment by UrsaarDev** [comment]
👋🏻 Good day, mates.
I make the following utilities based on Solidity & Rust with powerful frontend demonstration.
💻Dapps(Swap, Staking, Referral, Farm, Pool, Presale, Reflection, DAO ...)
💻NFT marketplaces (Opensea, Rarible, Metaplex)
💻Backend software
Leave msgs if you are in the demand of me.
